const $=id=>document.getElementById(id);
let prompts=[], source='file', connectedTabId=null;
const DEFAULTS={faAutoDownload:false,faLog:'',faAssets:{},faDelay:10,faSettings:{modelImage:'Nano Banana 2',aspectImage:'16:9',countImage:'x1',modelVideo:'Veo 3.1 Lite',duration:'8s'},faFlowTabId:null};
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function log(s){const t=new Date().toLocaleTimeString();$('log').textContent+=`\n[${t}] ${s}`;$('log').scrollTop=$('log').scrollHeight;chrome.storage.local.set({faLog:$('log').textContent});}
function render(){ $('count').textContent=prompts.length; $('preview').innerHTML=prompts.map((p,i)=>`<div>${i+1}. ${escapeHtml(p.slice(0,100))}</div>`).join(''); $('queue').innerHTML=prompts.map((p,i)=>`<div class="item"><span class="status" id="qs${i}">queued</span><b>#${i+1}</b> ${escapeHtml(p)}<div><button class="btn retry" data-retry="${i}">↻ Generate Again</button></div></div>`).join('');document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>retry(+b.dataset.retry));}
function loadPrompts(p){prompts=p;render();log(`Loaded ${p.length} prompt(s)`);}
function loadFile(f){f.text().then(t=>loadPrompts(t.split(/\n\s*\n|\n/).map(x=>x.trim()).filter(Boolean)));}
$('drop').onclick=()=>$('file').click();$('file').onchange=e=>{if(e.target.files[0])loadFile(e.target.files[0])};$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])loadFile(e.dataTransfer.files[0])};$('text').oninput=e=>loadPrompts(e.target.value.split(/\n\s*\n|\n/).map(x=>x.trim()).filter(Boolean));
document.querySelectorAll('[data-src]').forEach(b=>b.onclick=()=>{source=b.dataset.src;document.querySelectorAll('[data-src]').forEach(x=>x.classList.toggle('active',x===b));$('drop').style.display=source==='file'?'block':'none';$('text').style.display=source==='text'?'block':'none';});
function setDownload(v){chrome.storage.local.set({faAutoDownload:v});$('switch').textContent=v?'ON':'OFF';$('switch').classList.toggle('on',v);}
$('switch').onclick=()=>setDownload(!$('switch').classList.contains('on'));
async function refreshFlowTabs(){const tabs=await chrome.tabs.query({});const flows=tabs.filter(t=>/^https:\/\/(flow\.google\.com|labs\.google)/.test(t.url||''));const sel=$('flowTab');sel.innerHTML=flows.length?flows.map(t=>`<option value="${t.id}">${escapeHtml((t.title||'Flow').slice(0,45))} · ${t.id}</option>`).join(''):'<option value="">No Flow tab found</option>';const st=await chrome.storage.local.get(DEFAULTS);if(st.faFlowTabId && flows.some(t=>t.id===st.faFlowTabId)) sel.value=String(st.faFlowTabId);connectedTabId=sel.value?Number(sel.value):null;$('conn').textContent=connectedTabId?'Ready to connect':'No Flow tab';}
$('flowTab').onchange=()=>{connectedTabId=Number($('flowTab').value)||null;chrome.storage.local.set({faFlowTabId:connectedTabId});};
$('connect').onclick=async()=>{connectedTabId=Number($('flowTab').value)||null;if(!connectedTabId)return log('Buka tab Flow terlebih dahulu.');try{const r=await chrome.tabs.sendMessage(connectedTabId,{type:'FA_GET_STATE'});if(r?.ok){chrome.storage.local.set({faFlowTabId:connectedTabId});$('conn').textContent=`Connected · tab ${connectedTabId}`;log(`✓ Connected ke Flow tab ${connectedTabId}`);}else log('Flow tidak merespons. Refresh tab Flow lalu Connect lagi.');}catch(e){log('Tidak bisa konek: '+e.message+' — refresh tab Flow lalu Connect lagi.');}};
async function send(type,data={}){if(!connectedTabId){await refreshFlowTabs();}if(!connectedTabId){log('Tidak ada tab Flow yang terkoneksi.');return null;}try{return await chrome.tabs.sendMessage(connectedTabId,{type,...data});}catch(e){log('Koneksi Flow terputus: '+e.message);return null;}}
function getSettings(){return {modelImage:$('modelImage').value,aspectImage:$('aspectImage').value,countImage:$('countImage').value,modelVideo:$('modelVideo').value,duration:$('duration').value};}
function saveSettings(){const settings=getSettings();const delay=Math.max(0,Number($('delay').value)||0);chrome.storage.local.set({faSettings:settings,faDelay:delay});return {settings,delay};}
async function start(){if(!prompts.length)return log('Load prompts dulu.');const cfg=saveSettings();log(`Start ${prompts.length} prompt(s) · delay ${cfg.delay}s`);const r=await send('FA_SETUP_START',{prompts,settings:cfg.settings,delay:cfg.delay});if(!r)log('Start belum dikirim.');}
$('start').onclick=start;$('stop').onclick=async()=>{await send('FA_SETUP_STOP');log('Stop requested.');};$('clear').onclick=()=>{prompts=[];render();log('Queue cleared.');};$('clearLog').onclick=()=>{$('log').textContent='';chrome.storage.local.set({faLog:''});};
async function retry(i){const cfg=saveSettings();const r=await send('FA_SETUP_RETRY',{index:i,settings:cfg.settings,delay:cfg.delay});log(r?.ok?`Retry #${i+1} requested.`:`Retry #${i+1} gagal dikirim.`)}
function renderAssets(a){$('assets').innerHTML=Object.keys(a||{}).length?Object.entries(a).map(([n,v])=>`<div class="asset"><img src="${v.dataUrl||v.src||''}"><div>#${escapeHtml(n)}</div><small>${escapeHtml(v.mediaId||'')}</small></div>`).join(''):'<small>Belum ada asset.</small>';}
chrome.storage.onChanged.addListener(c=>{if(c.faAssets)renderAssets(c.faAssets.newValue||{});if(c.faLog)$('log').textContent=c.faLog.newValue||'';});
chrome.storage.local.get(DEFAULTS,s=>{setDownload(!!s.faAutoDownload);$('log').textContent=s.faLog||'';$('delay').value=s.faDelay??10;const x=s.faSettings||DEFAULTS.faSettings;for(const k of Object.keys(DEFAULTS.faSettings))if($(k))$(k).value=x[k]||DEFAULTS.faSettings[k];renderAssets(s.faAssets||{});connectedTabId=s.faFlowTabId||null;refreshFlowTabs();render();});
$('openSetup')?.addEventListener('click',()=>{});
render();refreshFlowTabs();
